# Generated by Django 3.0 on 2019-12-12 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191212_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
