# Generated by Django 3.0 on 2019-12-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_customer_delivery_boy_hr_queries_replier_report_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('CR', 'Customer'), ('HR', 'HR'), ('RM', 'Report_Manager'), ('DB', 'Delivery_Boy'), ('CQ', 'Customer_Queries_Replier')], max_length=10)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User_Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('CR', 'Customer'), ('HR', 'HR'), ('RM', 'Report_Manager'), ('DB', 'Delivery_Boy'), ('CQ', 'Customer_Queries_Replier')], default='CR', max_length=10)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
    ]
