# Generated by Django 3.0 on 2019-12-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20191216_0802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.AddField(
            model_name='product',
            name='dec_image1',
            field=models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='Image1'),
        ),
        migrations.AddField(
            model_name='product',
            name='dec_image2',
            field=models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='Image2'),
        ),
        migrations.AddField(
            model_name='product',
            name='dec_image3',
            field=models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='Image3'),
        ),
        migrations.AddField(
            model_name='product',
            name='dec_image4',
            field=models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='Image4'),
        ),
        migrations.AddField(
            model_name='product',
            name='dec_image5',
            field=models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='Image5'),
        ),
        migrations.AddField(
            model_name='product',
            name='display_image',
            field=models.ImageField(default=1, upload_to='product/', verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
