# Generated by Django 3.0 on 2019-12-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_reportproduct_is_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pickup_address',
            field=models.CharField(default='dhangadhi', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='zip',
            field=models.CharField(default=10900, max_length=100),
        ),
    ]
