# Generated by Django 3.0 on 2019-12-11 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191211_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Condition'),
        ),
    ]
