# Generated by Django 3.0 on 2019-12-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191212_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='dec_image1',
            field=models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='Image1'),
        ),
        migrations.AlterField(
            model_name='images',
            name='dec_image2',
            field=models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='Image2'),
        ),
        migrations.AlterField(
            model_name='images',
            name='dec_image3',
            field=models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='Image3'),
        ),
        migrations.AlterField(
            model_name='images',
            name='dec_image4',
            field=models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='Image4'),
        ),
        migrations.AlterField(
            model_name='images',
            name='dec_image5',
            field=models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='Image5'),
        ),
        migrations.AlterField(
            model_name='images',
            name='display_image',
            field=models.ImageField(upload_to='product/', verbose_name='Image'),
        ),
    ]
