# Generated by Django 3.0 on 2019-12-13 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_user_company_user_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Customer',
        ),
    ]
