# Generated by Django 3.0 on 2019-12-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_reportproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportproduct',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
