# Generated by Django 3.0 on 2019-12-21 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20191221_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='zip',
            new_name='zip_code',
        ),
    ]
